project_id = "tiyumtsvuqxolxngdfhz"

[functions.notify-ticket-created]
verify_jwt = true

[functions.hotmart-webhook]
verify_jwt = false

[functions.nutrition-chat]
verify_jwt = true

[functions.export-users-crm]
verify_jwt = true

[functions.configure-auth-security]
verify_jwt = true

[functions.generate-nutrition-plan]
verify_jwt = true